version: '3.9'

services:
  integration_tests:
    container_name: "tests"
    restart: on-failure
    depends_on:
      - calendar
      - scheduler
      - sender
    build:
      context: ..
      dockerfile: ./build/Dockerfile_test
    environment:
      - LEVEL=${LOGGER_LEVEL}
      - URL
      - NAME_TEST_Q

  sender:
    build:
      args:
        build_file: "cmd_test/sender"
    environment:
      - NAME_TEST_Q
      - AUTO_DELETE
      - DURABLE
      - MANDATORY
      - IMMEDIATE
      - EXCHANGE
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - NAME=${DB_NAME}
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}
