version: '3.9'

services:
  calendar:
    container_name: "calendar"
    restart: on-failure
    build:
      context: ..
      dockerfile: ./build/Dockerfile_calendar
    ports:
      - "8080:8080"
      - "8000:8000"
    depends_on:
      - migrate
    environment:
      # logger
      - LEVEL=${LOGGER_LEVEL}

      # grpc
      - GRPC_HOST
      - GRPC_PORT

      # http
      - HTTP_HOST
      - HTTP_PORT

      # sql
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - NAME=${DB_NAME}
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}

  scheduler:
    container_name: "scheduler"
    restart: on-failure
    build:
      context: ..
      dockerfile: ./build/Dockerfile_scheduler
    depends_on:
      - rabbit
      - migrate
    environment:
      # logger
      - LOGGER_LEVEL

      #tickers
      - ADD
      - CLEAR

      # rabbit
      - URL
      - NAME_Q
      - NO_WAIT
      - DURABLE
      - EXCLUSIVE
      - AUTO_DELETE
      - EXCHANGE
      - MANDATORY
      - IMMEDIATE

      # sql
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
      - NAME=${DB_NAME}
      - HOST=${DB_HOST}
      - PORT=${DB_PORT}

  sender:
    container_name: "sender"
    restart: on-failure
    build:
      context: ..
      dockerfile: ./build/Dockerfile_sender
    depends_on:
      - rabbit
    environment:
      # logger
      - LOGGER_LEVEL

      # rabbit
      - URL
      - NAME_Q
      - AUTO_ACK
      - EXCLUSIVE=${EXCLUSIVE_CONSUMER}
      - NO_LOCAL
      - NO_WAIT=${NO_WAIT_CONSUMER}

  db:
    container_name: "db"
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}

  migrate:
    container_name: "migrate"
    restart: on-failure
    image: migrate/migrate
    command: [/opt/migrate/goose, postgres, "host=${DB_HOST} password=${DB_PASSWORD} port=${DB_PORT} user=${DB_USER} dbname=${DB_NAME} sslmode=disable", up]
    build:
      context: ..
      dockerfile: ./build/Dockerfile_migrate
    depends_on:
      - db

  rabbit:
    restart: on-failure
    container_name: "rabbit"
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

